import 'package:meta/meta.dart';

import 'audience.dart';
import 'provenance.dart';

/// Editorial / discovery content models.
///
/// Design rule that runs through this file: **no programme name is hard-coded
/// anywhere.** `야구여왕 시즌 2` is a row in the `FeaturedTopic` / `Program`
/// tables supplied by remote static config, not an identifier in code. When
/// the season ends, the featured slot falls through to the next topic in the
/// priority list and the programme moves to an archive — no app release.

/// How a summary was produced. Always displayed next to the summary itself.
enum SummaryMethod {
  /// Written by a person.
  manual,

  /// Generated by a deterministic template from structured fields (scores,
  /// dates, counts). Safe because it cannot invent facts.
  template,

  /// Produced with model assistance. Must show the `AI 요약` badge, the
  /// generation time, its sources, and the review status.
  aiAssisted;

  static SummaryMethod parse(String? raw) => switch (raw) {
    'template' => SummaryMethod.template,
    'aiAssisted' => SummaryMethod.aiAssisted,
    _ => SummaryMethod.manual,
  };

  String get wireValue => name;

  String get labelKo => switch (this) {
    SummaryMethod.manual => '직접 작성',
    SummaryMethod.template => '자동 정리',
    SummaryMethod.aiAssisted => 'AI 요약',
  };

  /// AI-assisted summaries must carry a visible badge; the others do not need
  /// to shout, but the method is always available on the detail screen.
  bool get requiresBadge => this == SummaryMethod.aiAssisted;
}

enum ReviewStatus {
  pending,
  reviewed,
  rejected;

  static ReviewStatus parse(String? raw) => switch (raw) {
    'reviewed' => ReviewStatus.reviewed,
    'rejected' => ReviewStatus.rejected,
    _ => ReviewStatus.pending,
  };

  String get wireValue => name;

  String get labelKo => switch (this) {
    ReviewStatus.pending => '검수 전',
    ReviewStatus.reviewed => '검수 완료',
    ReviewStatus.rejected => '검수 반려',
  };
}

/// How complete the underlying data is. Shown wherever a number could be
/// mistaken for a full official tally.
@immutable
class DataCoverage {
  const DataCoverage({
    required this.observed,
    required this.expected,
    this.note,
    this.lastComputedAt,
  });

  /// How many source records we actually hold (e.g. games with box scores).
  final int observed;

  /// How many we believe exist for the scope. Zero means "unknown".
  final int expected;

  final String? note;
  final DateTime? lastComputedAt;

  bool get isUnknown => expected <= 0;

  double? get ratio => isUnknown ? null : (observed / expected).clamp(0.0, 1.0);

  bool get isComplete => !isUnknown && observed >= expected;

  String get labelKo {
    if (isUnknown) return '집계 범위 확인 중';
    if (isComplete) return '전체 $expected경기 집계';
    return '$expected경기 중 $observed경기 집계';
  }

  static const DataCoverage unknown = DataCoverage(observed: 0, expected: 0);
}

/// Content metadata shared by editorial entities.
@immutable
class ContentMeta {
  const ContentMeta({
    required this.provenance,
    required this.publishedAt,
    this.summaryMethod = SummaryMethod.manual,
    this.reviewStatus = ReviewStatus.reviewed,
    this.spoilerLevel = SpoilerLevel.none,
    this.coverage = DataCoverage.unknown,
    this.generatedAt,
  });

  final Provenance provenance;
  final DateTime publishedAt;
  final SummaryMethod summaryMethod;
  final ReviewStatus reviewStatus;
  final SpoilerLevel spoilerLevel;
  final DataCoverage coverage;

  /// When an automated summary was produced. Required for `aiAssisted`.
  final DateTime? generatedAt;

  bool get isDemo => provenance.isDemo;

  /// Whether this record may be shown.
  ///
  /// Deliberately identical to `_check_summary` in
  /// `scripts/validate/validate_data.py`, which is what actually gates
  /// publication: an `aiAssisted` summary needs a human review, a `template`
  /// summary is generated from structured fields and cannot invent anything,
  /// and `manual` text already had a person write it — that person *is* the
  /// human in the loop. A record a reviewer explicitly rejected is never shown,
  /// whatever produced it.
  ///
  /// It used to read `reviewed || template`, which withheld hand-written text
  /// as if a model had produced it. Every record in the shipped seed is
  /// `manual` + `pending`, so that rule hid whatever it was applied to — and it
  /// was applied at exactly one of the ten content types, which is why one
  /// section went dark while nine identical records rendered fine.
  bool get isPublishable {
    // `RecordVisibility` used to be parsed, stored, and checked nowhere, so a
    // record published as `private` or `hidden` rendered exactly like a public
    // one. Content rides in through `ContentSyncEngine`'s ten nested write
    // loops rather than the entity sync path, so it is enforced here — at the
    // gate the repository already consults on every read.
    if (provenance.visibility != RecordVisibility.public) return false;

    return switch (reviewStatus) {
      ReviewStatus.rejected => false,
      ReviewStatus.reviewed => true,
      ReviewStatus.pending => summaryMethod != SummaryMethod.aiAssisted,
    };
  }
}

/// The rotating "what should lead the app right now" slot.
///
/// Priority order lives in data (`featured_topics.json`), so an ended
/// broadcast falls through to the next entry automatically instead of leaving
/// a dead section on the home screen.
enum FeaturedTopicKind {
  /// A currently-airing broadcast or documentary.
  broadcast,

  /// National-team or international competition.
  international,

  /// A major domestic competition.
  domesticCompetition,

  /// A person's or team's story.
  story,

  /// This weekend's games near the user.
  nearbyGames,

  /// Getting-started / training content.
  gettingStarted;

  static FeaturedTopicKind parse(String? raw) => switch (raw) {
    'international' => FeaturedTopicKind.international,
    'domesticCompetition' => FeaturedTopicKind.domesticCompetition,
    'story' => FeaturedTopicKind.story,
    'nearbyGames' => FeaturedTopicKind.nearbyGames,
    'gettingStarted' => FeaturedTopicKind.gettingStarted,
    _ => FeaturedTopicKind.broadcast,
  };

  String get wireValue => name;

  /// Default fallback order when no topic declares an explicit priority.
  /// Mirrors §10 of the product brief.
  int get defaultPriority => switch (this) {
    FeaturedTopicKind.broadcast => 0,
    FeaturedTopicKind.international => 1,
    FeaturedTopicKind.domesticCompetition => 2,
    FeaturedTopicKind.story => 3,
    FeaturedTopicKind.nearbyGames => 4,
    FeaturedTopicKind.gettingStarted => 5,
  };
}

@immutable
class FeaturedTopic {
  const FeaturedTopic({
    required this.id,
    required this.kind,
    required this.title,
    required this.meta,
    this.subtitle,
    this.priority,
    this.programId,
    this.competitionId,
    this.storyClusterId,
    this.guideId,
    this.heroImageUrl,
    this.heroImageLicense = LicenseStatus.unknown,
    this.activeFrom,
    this.activeUntil,
    this.deletedAt,
  });

  final String id;
  final FeaturedTopicKind kind;
  final String title;
  final String? subtitle;

  /// Lower wins. Null falls back to [FeaturedTopicKind.defaultPriority].
  final int? priority;

  /// Exactly one of these points at the thing being featured.
  final String? programId;
  final String? competitionId;
  final String? storyClusterId;
  final String? guideId;

  final String? heroImageUrl;
  final LicenseStatus heroImageLicense;

  /// Outside this window the topic is inactive and something else leads.
  final DateTime? activeFrom;
  final DateTime? activeUntil;

  final ContentMeta meta;
  final DateTime? deletedAt;

  int get effectivePriority => priority ?? kind.defaultPriority;

  bool isActiveAt(DateTime now) {
    if (deletedAt != null) return false;
    final from = activeFrom;
    final until = activeUntil;
    if (from != null && now.isBefore(from)) return false;
    if (until != null && now.isAfter(until)) return false;
    return true;
  }

  bool get canShowHeroImage =>
      heroImageUrl != null &&
      heroImageUrl!.isNotEmpty &&
      heroImageLicense == LicenseStatus.permitted;
}

/// A broadcast programme / documentary series.
@immutable
class Program {
  const Program({
    required this.id,
    required this.title,
    required this.meta,
    this.broadcaster,
    this.officialUrl,
    this.streamingUrl,
    this.description,
    this.deletedAt,
  });

  final String id;
  final String title;

  /// e.g. `채널A`.
  final String? broadcaster;

  /// Official programme page. We link out; we never copy its body or images.
  final String? officialUrl;

  /// Official streaming/VOD page (e.g. TVING).
  final String? streamingUrl;

  final String? description;
  final ContentMeta meta;
  final DateTime? deletedAt;
}

@immutable
class ProgramSeason {
  const ProgramSeason({
    required this.id,
    required this.programId,
    required this.seasonNumber,
    required this.title,
    required this.meta,
    this.airDayOfWeek,
    this.airTimeMinuteOfDay,
    this.premiereDate,
    this.finaleDate,
    this.isActive = true,
    this.deletedAt,
  });

  final String id;
  final String programId;
  final int seasonNumber;
  final String title;

  /// 1 = Monday … 7 = Sunday (ISO). Used for "다음 방송" without inventing a
  /// specific episode that has not been announced.
  final int? airDayOfWeek;
  final int? airTimeMinuteOfDay;

  final DateTime? premiereDate;
  final DateTime? finaleDate;

  /// When false the season is archived: it moves out of the featured slot into
  /// "지난 시즌 다시보기".
  final bool isActive;

  final ContentMeta meta;
  final DateTime? deletedAt;

  /// How long a published weekly slot is trusted without fresh evidence.
  ///
  /// Three slots. A weekly programme that has not aired for three weeks is
  /// between seasons, has moved, or is over — and the data cannot tell us
  /// which. `finaleDate` and `isActive` both exist for this, and both are
  /// written once when a season is published and never revised, so neither
  /// notices that time has passed.
  static const Duration scheduleEvidenceWindow = Duration(days: 21);

  /// The next broadcast slot at or after [from], derived purely from the
  /// weekly schedule. Returns null when the schedule is unknown or the season
  /// has finished — we never guess an air date.
  ///
  /// [lastAiredAtKst] is the most recent episode we hold. Without it the
  /// projection runs on a published weekly slot alone, which never expires:
  /// the card would still promise "다음 방송 목요일 밤 10시" years after the
  /// programme ended, because nothing in the record says it did. A finale date
  /// is stronger evidence than recency and still wins where one exists.
  DateTime? nextAirSlot(DateTime from, {DateTime? lastAiredAtKst}) {
    final day = airDayOfWeek;
    final minute = airTimeMinuteOfDay;
    if (day == null || minute == null || !isActive) return null;
    final finale = finaleDate;

    if (finale == null) {
      // Before the premiere there is nothing to have aired yet, so the
      // premiere itself is the evidence.
      final evidence = lastAiredAtKst ?? premiereDate;
      if (evidence == null) return null;
      if (from.difference(evidence) > scheduleEvidenceWindow) return null;
    }
    var candidate = DateTime(
      from.year,
      from.month,
      from.day,
    ).add(Duration(minutes: minute));
    var guard = 0;
    while (guard++ < 8) {
      if (candidate.weekday == day && candidate.isAfter(from)) {
        if (finale != null && candidate.isAfter(finale)) return null;
        return candidate;
      }
      candidate = candidate.add(const Duration(days: 1));
    }
    return null;
  }
}

@immutable
class Episode {
  const Episode({
    required this.id,
    required this.programSeasonId,
    required this.episodeNumber,
    required this.meta,
    this.title,
    this.airedAt,
    this.officialUrl,
    this.deletedAt,
  });

  final String id;
  final String programSeasonId;
  final int episodeNumber;
  final String? title;

  /// Null when the episode is announced but not yet aired.
  final DateTime? airedAt;

  final String? officialUrl;
  final ContentMeta meta;
  final DateTime? deletedAt;

  bool hasAired(DateTime now) => airedAt != null && airedAt!.isBefore(now);
}

/// The two-depth recap. `30초 요약` answers three questions in one sentence
/// each; `3분 이해` adds background and links to real women's baseball.
@immutable
class EpisodeRecap {
  const EpisodeRecap({
    required this.id,
    required this.episodeId,
    required this.meta,
    this.teaser,
    this.whatHappened,
    this.whyItMatters,
    this.whatToWatchNext,
    this.background,
    this.realBaseballContext,
    this.deletedAt,
  });

  final String id;
  final String episodeId;

  /// Spoiler-free one-liner. Always safe to show.
  final String? teaser;

  // 30-second summary: three single sentences.
  final String? whatHappened;
  final String? whyItMatters;
  final String? whatToWatchNext;

  // 3-minute understanding.
  final String? background;
  final String? realBaseballContext;

  final ContentMeta meta;
  final DateTime? deletedAt;

  bool get hasQuickSummary =>
      whatHappened != null || whyItMatters != null || whatToWatchNext != null;

  bool get hasDeepSummary => background != null || realBaseballContext != null;

  /// [teaser] is written to be spoiler-free, so it is what we show when the
  /// user has chosen to hide results.
  String? maskedHeadline(SpoilerPolicy policy) =>
      policy.shouldMask(meta.spoilerLevel) ? teaser : (whatHappened ?? teaser);
}

/// An official clip or full-episode link. We store metadata and link out.
@immutable
class OfficialClip {
  const OfficialClip({
    required this.id,
    required this.title,
    required this.url,
    required this.meta,
    this.programSeasonId,
    this.episodeId,
    this.thumbnailUrl,
    this.thumbnailLicense = LicenseStatus.unknown,
    this.durationSeconds,
    this.channelName,
    this.deletedAt,
  });

  final String id;
  final String title;
  final String url;
  final String? programSeasonId;
  final String? episodeId;
  final String? thumbnailUrl;
  final LicenseStatus thumbnailLicense;
  final int? durationSeconds;
  final String? channelName;
  final ContentMeta meta;
  final DateTime? deletedAt;

  bool get canShowThumbnail =>
      thumbnailUrl != null &&
      thumbnailUrl!.isNotEmpty &&
      thumbnailLicense == LicenseStatus.permitted;
}

/// A running narrative that spans episodes / games / articles.
@immutable
class Storyline {
  const Storyline({
    required this.id,
    required this.title,
    required this.meta,
    this.summary,
    this.programSeasonId,
    this.deletedAt,
  });

  final String id;
  final String title;
  final String? summary;
  final String? programSeasonId;
  final ContentMeta meta;
  final DateTime? deletedAt;
}

/// A person worth watching in a given episode or storyline.
///
/// Note this is *not* the same as [Person] in `domain.dart`: a broadcast
/// participant is only linked to a real player record when that link has been
/// officially confirmed. Unconfirmed links are simply absent.
@immutable
class FeaturedPerson {
  const FeaturedPerson({
    required this.id,
    required this.displayName,
    required this.meta,
    this.episodeId,
    this.storylineId,
    this.role,
    this.whyWatch,
    this.linkedPersonId,
    this.linkedTeamId,
    this.photoUrl,
    this.photoLicense = LicenseStatus.unknown,
    this.deletedAt,
  });

  final String id;
  final String displayName;
  final String? episodeId;
  final String? storylineId;

  /// e.g. `투수`, `감독`, `코치`.
  final String? role;

  final String? whyWatch;

  /// Set only when the connection to a real player / team record has been
  /// officially confirmed. We never infer a relationship.
  final String? linkedPersonId;
  final String? linkedTeamId;

  final String? photoUrl;
  final LicenseStatus photoLicense;
  final ContentMeta meta;
  final DateTime? deletedAt;

  bool get hasConfirmedRealLink =>
      linkedPersonId != null || linkedTeamId != null;

  bool get canShowPhoto =>
      photoUrl != null &&
      photoUrl!.isNotEmpty &&
      photoLicense == LicenseStatus.permitted;
}

/// What a piece of content points at. Uses canonical ids, never name strings,
/// so links survive an upstream API change.
enum ContentEntityKind {
  team,
  person,
  competition,
  season,
  game,
  venue,
  program,
  programSeason,
  episode,
  storyCluster,
  guide;

  static ContentEntityKind parse(String? raw) {
    for (final k in ContentEntityKind.values) {
      if (k.name == raw) return k;
    }
    return ContentEntityKind.team;
  }

  String get wireValue => name;
}

/// Why two things are linked. Keeps "appeared in" distinct from "is actually
/// this player", which matters a great deal for a broadcast.
enum ContentLinkRelation {
  /// Officially confirmed identity link.
  isEntity,

  /// Mentioned or appeared, without an identity claim.
  mentions,

  /// Background reading.
  relatedContext,

  /// The opposing/related real team in a broadcast fixture.
  opponent;

  static ContentLinkRelation parse(String? raw) => switch (raw) {
    'mentions' => ContentLinkRelation.mentions,
    'relatedContext' => ContentLinkRelation.relatedContext,
    'opponent' => ContentLinkRelation.opponent,
    _ => ContentLinkRelation.isEntity,
  };

  String get wireValue => name;

  String get labelKo => switch (this) {
    ContentLinkRelation.isEntity => '공식 확인된 연결',
    ContentLinkRelation.mentions => '언급',
    ContentLinkRelation.relatedContext => '관련 배경',
    ContentLinkRelation.opponent => '상대 팀',
  };
}

@immutable
class ContentEntityLink {
  const ContentEntityLink({
    required this.id,
    required this.fromKind,
    required this.fromId,
    required this.toKind,
    required this.toId,
    required this.relation,
    this.label,
    this.confirmedSourceUrl,
  });

  final String id;
  final ContentEntityKind fromKind;
  final String fromId;
  final ContentEntityKind toKind;
  final String toId;
  final ContentLinkRelation relation;
  final String? label;

  /// Required for [ContentLinkRelation.isEntity]: an identity claim needs a
  /// citation. Validation rejects such a link without one.
  final String? confirmedSourceUrl;

  bool get isConfirmedIdentity =>
      relation == ContentLinkRelation.isEntity &&
      confirmedSourceUrl != null &&
      confirmedSourceUrl!.isNotEmpty;
}

/// One source article inside a story cluster.
@immutable
class StorySource {
  const StorySource({
    required this.id,
    required this.storyClusterId,
    required this.title,
    required this.url,
    required this.publishedAt,
    this.outlet,

    /// Only the description the search API itself returned. Never scraped body
    /// text, never the outlet's images.
    this.apiDescription,
  });

  final String id;
  final String storyClusterId;
  final String title;
  final String url;
  final DateTime publishedAt;
  final String? outlet;
  final String? apiDescription;
}

/// Several articles about the same event, presented once.
@immutable
class StoryCluster {
  const StoryCluster({
    required this.id,
    required this.title,
    required this.meta,
    required this.firstPublishedAt,
    required this.lastUpdatedAt,
    this.shortSummary,
    this.whyItMatters,
    this.beginnerContext,
    this.sources = const <StorySource>[],
    this.links = const <ContentEntityLink>[],
    this.isTopStory = false,
    this.deletedAt,
  });

  final String id;
  final String title;

  /// `30초 요약`
  final String? shortSummary;
  final String? whyItMatters;

  /// Extra sentence for readers new to the sport. Hidden when the user has
  /// turned beginner explanations off.
  final String? beginnerContext;

  final List<StorySource> sources;
  final List<ContentEntityLink> links;

  final DateTime firstPublishedAt;
  final DateTime lastUpdatedAt;

  /// True for the non-personalised `모두가 알아둘 주요 소식` rail, which exists
  /// to keep a personalised feed from becoming a filter bubble.
  final bool isTopStory;

  final ContentMeta meta;
  final DateTime? deletedAt;

  int get sourceCount => sources.length;

  /// A cluster with several outlets is worth showing as "N개 매체 보도".
  bool get hasMultipleSources => sources.length > 1;

  String? get primaryUrl => sources.isEmpty ? null : sources.first.url;
}

/// Short contextual explainer, shown inline rather than as an encyclopaedia.
enum GuideKind {
  /// "여자야구 1분 이해"
  oneMinuteIntro,

  /// "이 기록은 무엇인가요?"
  statExplainer,

  /// "이번 경기에서 볼 것"
  watchFor,

  /// "처음 직관할 때 알아둘 것"
  firstVisit,

  /// "왜 중요한가요?"
  whyItMatters,

  /// Baseball term glossary entry.
  term;

  static GuideKind parse(String? raw) {
    for (final k in GuideKind.values) {
      if (k.name == raw) return k;
    }
    return GuideKind.oneMinuteIntro;
  }

  String get wireValue => name;
}

@immutable
class BeginnerGuide {
  const BeginnerGuide({
    required this.id,
    required this.kind,
    required this.title,
    required this.body,
    required this.meta,
    this.anchorKey,
    this.readSeconds,
    this.deletedAt,
  });

  final String id;
  final GuideKind kind;
  final String title;
  final String body;

  /// Where this attaches, e.g. `stat:era`, `screen:game_detail`. Lets the app
  /// surface the right explainer in context instead of in a separate manual.
  final String? anchorKey;

  final int? readSeconds;
  final ContentMeta meta;
  final DateTime? deletedAt;
}

/// Whether a game can actually be watched in person.
enum AttendanceStatus {
  /// Confirmed open to spectators.
  open,

  /// Confirmed closed / restricted.
  closed,

  /// Not confirmed. This is the default and it is displayed as
  /// "관람 가능 여부 확인 필요" — never assumed to be free and open.
  needsConfirmation;

  static AttendanceStatus parse(String? raw) => switch (raw) {
    'open' => AttendanceStatus.open,
    'closed' => AttendanceStatus.closed,
    _ => AttendanceStatus.needsConfirmation,
  };

  String get wireValue => name;

  String get labelKo => switch (this) {
    AttendanceStatus.open => '관람 가능',
    AttendanceStatus.closed => '관람 불가',
    AttendanceStatus.needsConfirmation => '관람 가능 여부 확인 필요',
  };
}

/// Spectator information for a game. Every field is nullable and every unknown
/// renders as "확인 필요" rather than a guess.
@immutable
class AttendanceInfo {
  const AttendanceInfo({
    required this.gameId,
    required this.status,
    required this.provenance,
    this.admissionNote,
    this.entryProcedure,
    this.seatingNote,
    this.parkingUrl,
    this.transitUrl,
    this.restroomAvailable,
    this.concessionAvailable,
    this.familyFriendlyConfirmed = false,
    this.confirmedAt,
  });

  final String gameId;
  final AttendanceStatus status;

  /// Free text from the organiser, e.g. "무료 개방". Absent means unknown —
  /// the UI must not infer "free".
  final String? admissionNote;

  final String? entryProcedure;
  final String? seatingNote;

  /// Only present when an official page confirms it.
  final String? parkingUrl;
  final String? transitUrl;

  final bool? restroomAvailable;
  final bool? concessionAvailable;

  /// Only true when explicitly confirmed; we never infer suitability.
  final bool familyFriendlyConfirmed;

  final DateTime? confirmedAt;
  final Provenance provenance;

  bool get isConfirmed => status != AttendanceStatus.needsConfirmation;

  bool get hasAdmissionInfo =>
      admissionNote != null && admissionNote!.trim().isNotEmpty;
}
